org: duckaccessory
app: alura-activities
service: aws-node-http-api-project
frameworkVersion: '3'

params:
  default:
    dbName: alura-serveless
  dev: 
    connectionString: mongodb://localhost:27017/${self:params.default.dbName}

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    MONGODB_CONNECTIONSTRING: ${self:params.dev.connectionString}
    MONGODB_DB_NAME: ${self:params.default.dbName}


functions:
  sendResponse:
    handler: api/handlers.sendResponse
    events:
      - httpApi:
          path: /api/results
          method: post
          request:
            schemas:
              application/json: ${file(./schemas/sendResponse.json)}
  getResult:
    handler: api/handlers.getResult
    events:
      - httpApi: 
          path: /api/results/{id}
          method: get

plugins:
  - serverless-offline
